import ultraciteFmt from "ultracite/oxfmt";
import ultraciteLint from "ultracite/oxlint/core";
import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    ...ultraciteFmt,
    ignorePatterns: [
      ...(ultraciteFmt.ignorePatterns ?? []),
      "lib/**",
      "coverage/**",
    ],
    sortPackageJson: true,
  },
  lint: {
    extends: [ultraciteLint],
    ignorePatterns: ["lib/**", "coverage/**"],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    overrides: [
      {
        files: ["test/**/*.ts", "scripts/**/*.ts"],
        rules: {
          "import/namespace": "off",
          "no-console": "off",
          "no-process-exit": "off",
          "promise/prefer-await-to-callbacks": "off",
          "typescript/no-non-null-assertion": "off",
          "typescript/no-unsafe-argument": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-member-access": "off",
          "typescript/no-unsafe-return": "off",
          "typescript/strict-boolean-expressions": "off",
        },
      },
    ],
    rules: {
      complexity: "off",
      "consistent-type-specifier-style": "off",
      curly: "off",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "max-classes-per-file": "off",
      "max-nested-callbacks": "off",
      "no-await-in-loop": "warn",
      "no-eq-null": "off",
      "no-inline-comments": "off",
      "no-use-before-define": "off",
      "node/callback-return": "off",
      "prefer-named-capture-group": "off",
      "require-await": "warn",
      "require-param-description": "off",
      "require-returns-description": "off",
      "require-unicode-regexp": "off",
      "typescript/await-thenable": "error",
      "typescript/no-explicit-any": "warn",
      "typescript/no-floating-promises": "error",
      "typescript/no-for-in-array": "error",
      "typescript/no-implied-eval": "error",
      "typescript/no-misused-promises": "error",
      "typescript/no-non-null-assertion": "warn",
      "typescript/no-unsafe-argument": "warn",
      "typescript/no-unsafe-assignment": "warn",
      "typescript/no-unsafe-call": "warn",
      "typescript/no-unsafe-enum-comparison": "warn",
      "typescript/no-unsafe-function-type": "warn",
      "typescript/no-unsafe-member-access": "warn",
      "typescript/no-unsafe-return": "warn",
      "typescript/no-unsafe-type-assertion": "warn",
      "typescript/only-throw-error": "error",
      "typescript/prefer-nullish-coalescing": "warn",
      "typescript/prefer-promise-reject-errors": "error",
      "typescript/promise-function-async": "warn",
      "typescript/return-await": "warn",
      "typescript/strict-boolean-expressions": "warn",
      "unicorn/filename-case": "off",
      "unicorn/prefer-export-from": "off",
    },
  },
  pack: [
    {
      clean: true,
      dts: true,
      format: ["esm"],
      outDir: "lib",
      platform: "node",
      sourcemap: false,
      target: "node24",
    },
    {
      banner:
        'window.__ModuleLoader__.load({\n  id: "dsh-opencode",\n  factory: (require) => {\n    var module = { exports: {} };\n    var exports = module.exports;',
      clean: false,
      deps: {
        neverBundle: [
          "react",
          "react/jsx-runtime",
          "@deepseek-ai/dsh-client-ui-primitives",
        ],
      },
      dts: false,
      entry: { client: "src/settings-page.tsx" },
      footer: "    return module.exports;\n  },\n});",
      format: ["cjs"],
      outDir: "lib",
      platform: "browser",
      sourcemap: false,
    },
  ],
  test: {
    include: ["test/**/*.test.ts"],
  },
});
