/**
 * GENERATED by `scripts/generate-go-limits.ts` — do not edit by hand.
 *
 * The Go plan's monthly allowance per model, in whole US dollars, for both tiers:
 * `go` is the $10/month plan, `goPlus` the $40/month one. Source of truth is
 * OpenCode's own Go documentation; `pnpm run limits:shim` reports staleness and
 * `--write` rewrites this file.
 *
 * 30 models.
 */

import type { ModelAllowance } from "./go-limits.ts";

export const GO_MODEL_LIMITS: Readonly<Record<string, ModelAllowance>> = {
  "claude-haiku-5.5": {
    go: 15,
    goPlus: 60,
    name: "Claude Haiku 5.5 (≤ 100K tokens)",
  },
  "deepseek-v4-flash": {
    go: 30,
    goPlus: 120,
    name: "DeepSeek V4 Flash (Off-Peak)",
  },
  "deepseek-v4-flash-vision-exp": {
    go: 15,
    goPlus: 60,
    name: "DeepSeek V4 Flash Vision Exp (Off-Peak)",
  },
  "deepseek-v4-pro": {
    go: 15,
    goPlus: 60,
    name: "DeepSeek V4 Pro (Off-Peak)",
  },
  "deepseek-v4.1-flash": {
    go: 60,
    goPlus: 120,
    name: "DeepSeek V4.1 Flash (Off-Peak)",
  },
  "glm-5.2": {
    go: 60,
    goPlus: 180,
    name: "GLM-5.2",
  },
  "glm-5.3": {
    go: 15,
    goPlus: 120,
    name: "GLM-5.3",
  },
  "glm-5.3-flash": {
    go: 60,
    goPlus: 180,
    name: "GLM-5.3-Flash",
  },
  "gpt-5.6-luna": {
    go: 15,
    goPlus: 60,
    name: "GPT 5.6 Luna (≤ 272K tokens)",
  },
  "gpt-6-luna": {
    go: 15,
    goPlus: 60,
    name: "GPT 6 Luna (≤ 272K tokens)",
  },
  "grok-4.6": {
    go: 15,
    goPlus: 60,
    name: "Grok 4.6 (≤ 200K tokens)",
  },
  "grok-4.7": {
    go: 15,
    goPlus: 60,
    name: "Grok 4.7 (≤ 200K tokens)",
  },
  hy3: {
    go: 60,
    goPlus: 240,
    name: "Hy3",
  },
  "hy4-preview": {
    go: 30,
    goPlus: 120,
    name: "Hy4 preview",
  },
  "kimi-k2.6": {
    go: 60,
    goPlus: 240,
    name: "Kimi K2.6",
  },
  "kimi-k2.7-code": {
    go: 60,
    goPlus: 180,
    name: "Kimi K2.7 Code",
  },
  "kimi-k3": {
    go: 15,
    goPlus: 60,
    name: "Kimi K3",
  },
  "longcat-2.0": {
    go: 60,
    goPlus: 240,
    name: "LongCat-2.0",
  },
  "mimo-v2.5": {
    go: 60,
    goPlus: 120,
    name: "MiMo-V2.5",
  },
  "mimo-v2.5-pro": {
    go: 15,
    goPlus: 60,
    name: "MiMo-V2.5-Pro",
  },
  "mimo-v2.6-flash": {
    go: 60,
    goPlus: 120,
    name: "MiMo-V2.6-Flash",
  },
  "mimo-v2.6-pro": {
    go: 15,
    goPlus: 60,
    name: "MiMo-V2.6-Pro",
  },
  "minimax-m2.7": {
    go: 60,
    goPlus: 240,
    name: "MiniMax M2.7",
  },
  "minimax-m3": {
    go: 60,
    goPlus: 180,
    name: "MiniMax M3",
  },
  "muse-spark-1.2-contributor": {
    go: 60,
    goPlus: 120,
    name: "Muse Spark 1.2 Contributor",
  },
  "muse-spark-1.3-contributor": {
    go: 60,
    goPlus: 120,
    name: "Muse Spark 1.3 Contributor",
  },
  "qwen3.7-plus": {
    go: 60,
    goPlus: 180,
    name: "Qwen3.7 Plus (≤ 256K tokens)",
  },
  "qwen3.8-flash": {
    go: 30,
    goPlus: 90,
    name: "Qwen3.8 Flash",
  },
  "qwen3.8-max": {
    go: 15,
    goPlus: 60,
    name: "Qwen3.8 Max",
  },
  "space-bunny": {
    go: 30,
    goPlus: 120,
    name: "Space Bunny",
  },
};
